name: Coverage

on:
  pull_request:
  push:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./target/llvm-cov/html"